# Generated by Django 5.2.17 on 2026-09-22 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="kind",
            field=models.CharField(
                choices=[
                    ("review", "确认招人要求"),
                    ("revise", "补充招人要求"),
                    ("start", "确认后开始招聘"),
                ],
                default="review",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.profileversion"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("profile", "kind"), name="one_profile_task_kind"
            ),
        ),
    ]
