# Generated by Django 5.2.17 on 2026-09-22 17:14

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0002_task_kind_alter_task_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="request_id",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                fields=("owner", "request_id"), name="one_job_creation_request"
            ),
        ),
    ]
