# Generated by Django 5.2.17 on 2026-09-22 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0003_job_request_id_job_one_job_creation_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="active_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="recruitment.profileversion",
            ),
        ),
        migrations.AddField(
            model_name="profileversion",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profileversion",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="recruitment.membership",
            ),
        ),
    ]
