# Generated by Django 5.2.17 on 2026-09-22 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0004_job_active_profile_profileversion_submitted_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileClarification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.CharField(max_length=1000)),
                ("request_key", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待回答"),
                            ("answered", "已回答"),
                            ("withdrawn", "已撤回"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("answer", models.CharField(blank=True, max_length=2000)),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="task",
            name="one_profile_task_kind",
        ),
        migrations.AlterField(
            model_name="task",
            name="kind",
            field=models.CharField(
                choices=[
                    ("review", "确认招人要求"),
                    ("revise", "补充招人要求"),
                    ("start", "确认后开始招聘"),
                    ("clarify", "回答招人要求问题"),
                    ("clarify_followup", "整理澄清答复"),
                ],
                default="review",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="profileclarification",
            name="assignee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="recruitment.membership",
            ),
        ),
        migrations.AddField(
            model_name="profileclarification",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.organization"
            ),
        ),
        migrations.AddField(
            model_name="profileclarification",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clarifications",
                to="recruitment.profileversion",
            ),
        ),
        migrations.AddField(
            model_name="profileclarification",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="recruitment.membership",
            ),
        ),
        migrations.AddField(
            model_name="profileclarification",
            name="requirement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.profilerequirement"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="clarification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="recruitment.profileclarification",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("clarification__isnull", True)),
                fields=("profile", "kind"),
                name="one_profile_task_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("clarification__isnull", False)),
                fields=("clarification", "kind"),
                name="one_clarification_task_kind",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("clarification__isnull", False),
                        ("kind__in", ["clarify", "clarify_followup"]),
                    ),
                    models.Q(
                        ("clarification__isnull", True), ("kind__in", ["review", "revise", "start"])
                    ),
                    _connector="OR",
                ),
                name="task_has_expected_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="profileclarification",
            constraint=models.UniqueConstraint(
                fields=("organization", "request_key"), name="one_clarification_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="profileclarification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("answered_at__isnull", False),
                        ("status", "answered"),
                        models.Q(("answer", ""), _negated=True),
                    ),
                    models.Q(
                        ("answer", ""),
                        ("answered_at__isnull", True),
                        ("status__in", ["pending", "withdrawn"]),
                    ),
                    _connector="OR",
                ),
                name="clarification_answer_complete",
            ),
        ),
    ]
