# Generated by Django 5.2.17 on 2026-09-23 02:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0005_profileclarification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_no", models.PositiveIntegerField()),
                ("source", models.CharField(max_length=200)),
                ("stage", models.CharField(default="pending_review", max_length=24)),
                ("version", models.PositiveIntegerField(default=1)),
                ("closed_at", models.DateTimeField(null=True)),
                ("close_reason", models.CharField(blank=True, max_length=2000)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_key", models.UUIDField()),
                ("source", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationResume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(db_index=True, max_length=100)),
                ("phone", models.CharField(blank=True, db_index=True, max_length=32)),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                ("contact_note", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(max_length=200)),
                ("request_key", models.UUIDField()),
                ("total", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ImportItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_key", models.UUIDField()),
                ("identity_note", models.CharField(blank=True, max_length=1000)),
                ("identity_payload", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="ResumeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_key", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("original_name", models.CharField(max_length=255)),
                ("file_type", models.CharField(max_length=10)),
                ("size", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("access_state", models.CharField(default="active", max_length=20)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResumeParse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                ("parser_version", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=20)),
                ("text", models.TextField(blank=True)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("request_key", models.UUIDField()),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="ReviewDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_key", models.UUIDField()),
                ("action", models.CharField(max_length=20)),
                ("reason", models.CharField(max_length=2000)),
                ("due_at", models.DateTimeField(null=True)),
                ("previous_stage", models.CharField(max_length=24)),
                ("result_stage", models.CharField(max_length=24)),
                ("input_parses", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("from_stage", models.CharField(blank=True, max_length=24)),
                ("to_stage", models.CharField(max_length=24)),
                ("request_key", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="task",
            name="task_has_expected_source",
        ),
        migrations.AddField(
            model_name="task",
            name="due_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="departmentrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("hr", "HR"),
                    ("manager", "用人负责人"),
                    ("supervisor", "招聘主管"),
                    ("resume_download", "简历原件下载"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="kind",
            field=models.CharField(
                choices=[
                    ("app_review", "复核应聘材料"),
                    ("need_info", "补充应聘材料"),
                    ("schedule", "安排面试"),
                    ("review", "确认招人要求"),
                    ("revise", "补充招人要求"),
                    ("start", "确认后开始招聘"),
                    ("clarify", "回答招人要求问题"),
                    ("clarify_followup", "整理澄清答复"),
                ],
                default="review",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="recruitment.profileversion",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.job"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.organization"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.membership"
            ),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="application",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="recruitment.application"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="application",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="recruitment.application"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("application__isnull", True),
                        ("profile__isnull", False),
                        models.Q(
                            models.Q(
                                ("clarification__isnull", False),
                                ("kind__in", ["clarify", "clarify_followup"]),
                            ),
                            models.Q(
                                ("clarification__isnull", True),
                                ("kind__in", ["review", "revise", "start"]),
                            ),
                            _connector="OR",
                        ),
                    ),
                    models.Q(
                        ("application__isnull", False),
                        ("clarification__isnull", True),
                        ("kind__in", ["app_review", "need_info", "schedule"]),
                        ("profile__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="task_has_expected_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("application__isnull", False), ("status", "pending")),
                fields=("application", "kind"),
                name="one_pending_application_task",
            ),
        ),
        migrations.AddField(
            model_name="applicationentry",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.membership"
            ),
        ),
        migrations.AddField(
            model_name="applicationentry",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.application"
            ),
        ),
        migrations.AddField(
            model_name="applicationentry",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.organization"
            ),
        ),
        migrations.AddField(
            model_name="applicationresume",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resumes",
                to="recruitment.application",
            ),
        ),
        migrations.AddField(
            model_name="applicationresume",
            name="assigned_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.membership"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.membership"
            ),
        ),
        migrations.AddField(
            model_name="candidate",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.organization"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="recruitment.candidate",
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.membership"
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.job"
            ),
        ),
        migrations.AddField(
            model_name="importbatch",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.organization"
            ),
        ),
        migrations.AddField(
            model_name="importitem",
            name="application",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="recruitment.application"
            ),
        ),
        migrations.AddField(
            model_name="importitem",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="recruitment.importbatch",
            ),
        ),
        migrations.AddField(
            model_name="importitem",
            name="confirmed_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="recruitment.membership"
            ),
        ),
        migrations.AddField(
            model_name="resumedocument",
            name="candidate",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="recruitment.candidate"
            ),
        ),
        migrations.AddField(
            model_name="resumedocument",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.organization"
            ),
        ),
        migrations.AddField(
            model_name="resumedocument",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.membership"
            ),
        ),
        migrations.AddField(
            model_name="importitem",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.resumedocument"
            ),
        ),
        migrations.AddField(
            model_name="resumeparse",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.membership"
            ),
        ),
        migrations.AddField(
            model_name="resumeparse",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parses",
                to="recruitment.resumedocument",
            ),
        ),
        migrations.AddField(
            model_name="applicationresume",
            name="parse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.resumeparse"
            ),
        ),
        migrations.AddField(
            model_name="reviewdecision",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to="recruitment.application",
            ),
        ),
        migrations.AddField(
            model_name="reviewdecision",
            name="followup_owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="recruitment.membership",
            ),
        ),
        migrations.AddField(
            model_name="reviewdecision",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="recruitment.profileversion",
            ),
        ),
        migrations.AddField(
            model_name="reviewdecision",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.membership"
            ),
        ),
        migrations.AddField(
            model_name="stageevent",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="recruitment.membership"
            ),
        ),
        migrations.AddField(
            model_name="stageevent",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stage_events",
                to="recruitment.application",
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationentry",
            constraint=models.UniqueConstraint(
                fields=("organization", "request_key"), name="one_entry_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                fields=("candidate", "job", "attempt_no"), name="application_attempt"
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(
                condition=models.Q(("closed_at__isnull", True)),
                fields=("candidate", "job"),
                name="one_active_application",
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_no__gte", 1)), name="positive_attempt"
            ),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("closed_at__isnull", False),
                        ("stage", "closed"),
                        models.Q(("close_reason", ""), _negated=True),
                    ),
                    models.Q(
                        ("close_reason", ""),
                        ("closed_at__isnull", True),
                        ("stage__in", ["pending_review", "needs_information", "ready_to_schedule"]),
                    ),
                    _connector="OR",
                ),
                name="application_closure",
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.UniqueConstraint(
                fields=("organization", "request_key"), name="one_import_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="importbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("total__gte", 1), ("total__lte", 20)), name="batch_size"
            ),
        ),
        migrations.AddConstraint(
            model_name="importitem",
            constraint=models.UniqueConstraint(
                fields=("batch", "request_key"), name="one_import_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="resumeparse",
            constraint=models.UniqueConstraint(
                fields=("document", "version"), name="parse_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="resumeparse",
            constraint=models.UniqueConstraint(
                fields=("document", "request_key"), name="parse_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="applicationresume",
            constraint=models.UniqueConstraint(
                fields=("application", "parse"), name="application_resume_input"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewdecision",
            constraint=models.UniqueConstraint(
                fields=("application", "request_key"), name="one_review_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="stageevent",
            constraint=models.UniqueConstraint(
                fields=("application", "request_key"), name="one_stage_event"
            ),
        ),
    ]
