# Generated by Django 5.2.17 on 2026-09-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0006_application_applicationentry_applicationresume_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["organization", "stage", "job"], name="application_work_queue"
            ),
        ),
        migrations.AddIndex(
            model_name="candidate",
            index=models.Index(fields=["organization", "display_name"], name="candidate_org_name"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["assignee", "status", "due_at"], name="task_work_queue"),
        ),
        migrations.AddConstraint(
            model_name="resumedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(("size__gt", 0), ("size__lte", 20971520)),
                name="resume_file_size",
            ),
        ),
        migrations.AddConstraint(
            model_name="resumedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("access_state__in", ["active", "quarantine", "deleted"]),
                    ("file_type__in", ["pdf", "docx"]),
                ),
                name="resume_file_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="resumeparse",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="positive_parse_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="resumeparse",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("error", ""),
                        ("status", "succeeded"),
                        models.Q(("text", ""), _negated=True),
                    ),
                    models.Q(
                        ("status", "failed"), ("text", ""), models.Q(("error", ""), _negated=True)
                    ),
                    _connector="OR",
                ),
                name="parse_has_result",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewdecision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("action", "need_info"),
                        ("due_at__isnull", False),
                        ("followup_owner__isnull", False),
                    ),
                    models.Q(
                        ("action__in", ["advance", "reject", "supplement", "withdraw"]),
                        ("due_at__isnull", True),
                        ("followup_owner__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="review_followup_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("kind", "need_info"), _negated=True),
                    ("due_at__isnull", False),
                    _connector="OR",
                ),
                name="followup_has_deadline",
            ),
        ),
    ]
