# Generated by Django 5.2.17 on 2026-09-24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0007_application_application_work_queue_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="application",
            name="application_closure",
        ),
        migrations.AlterField(
            model_name="application",
            name="stage",
            field=models.CharField(default="pending_review", max_length=24),
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("closed_at__isnull", False),
                        ("stage", "closed"),
                        models.Q(("close_reason", ""), _negated=True),
                    ),
                    models.Q(
                        ("close_reason", ""),
                        ("closed_at__isnull", True),
                        (
                            "stage__in",
                            [
                                "pending_review",
                                "needs_information",
                                "ready_to_schedule",
                                "interviewing",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="application_closure",
            ),
        ),
        migrations.AlterField(
            model_name="departmentrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("hr", "HR"),
                    ("manager", "用人负责人"),
                    ("interviewer", "面试官"),
                    ("supervisor", "招聘主管"),
                    ("resume_download", "简历原件下载"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("round_no", models.PositiveSmallIntegerField()),
                ("purpose", models.CharField(max_length=200)),
                ("request_key", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unscheduled", "未排期"),
                            ("pending_confirmation", "待确认"),
                            ("confirmed", "已确认"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="unscheduled",
                        max_length=24,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.CharField(blank=True, max_length=1000)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interviews",
                        to="recruitment.application",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organized_interviews",
                        to="recruitment.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recruitment.organization",
                    ),
                ),
            ],
            options={"ordering": ["-id"]},
        ),
        migrations.CreateModel(
            name="InterviewRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveSmallIntegerField()),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("timezone", models.CharField(max_length=64)),
                (
                    "mode",
                    models.CharField(
                        choices=[("onsite", "现场"), ("video", "视频"), ("phone", "电话")],
                        max_length=16,
                    ),
                ),
                ("location", models.TextField(blank=True)),
                ("meeting_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("current", "当前"),
                            ("superseded", "已替代"),
                            ("cancelled", "已取消"),
                        ],
                        default="current",
                        max_length=16,
                    ),
                ),
                ("change_reason", models.TextField(blank=True)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="recruitment.interview",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recruitment.organization",
                    ),
                ),
            ],
            options={"ordering": ["-version"]},
        ),
        migrations.CreateModel(
            name="InterviewParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                ("duty", models.CharField(default="interviewer", max_length=32)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="recruitment.membership",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participants",
                        to="recruitment.interviewrevision",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="interview",
            name="current_revision",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="recruitment.interviewrevision",
            ),
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(fields=["organization", "status"], name="interview_org_status"),
        ),
        migrations.AddIndex(
            model_name="interviewrevision",
            index=models.Index(
                fields=["organization", "starts_at", "ends_at"], name="interview_slot_index"
            ),
        ),
        migrations.AddConstraint(
            model_name="interview",
            constraint=models.CheckConstraint(
                condition=models.Q(("round_no__gte", 1)), name="positive_interview_round"
            ),
        ),
        migrations.AddConstraint(
            model_name="interview",
            constraint=models.UniqueConstraint(
                fields=("organization", "request_key"), name="one_interview_schedule_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="interviewrevision",
            constraint=models.UniqueConstraint(
                fields=("interview", "version"), name="interview_revision_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="interviewrevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "current")),
                fields=("interview",),
                name="one_current_interview_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="interviewrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("starts_at__lt", models.F("ends_at"))),
                name="interview_time_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="interviewrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("mode", "onsite"), models.Q(("location", ""), _negated=True)),
                    models.Q(("mode", "video"), models.Q(("meeting_url", ""), _negated=True)),
                    ("mode", "phone"),
                    _connector="OR",
                ),
                name="interview_mode_details",
            ),
        ),
        migrations.AddConstraint(
            model_name="interviewparticipant",
            constraint=models.UniqueConstraint(
                fields=("revision", "membership"), name="one_interview_participant"
            ),
        ),
    ]
