# Generated by Django 5.2.17 on 2026-09-28

from django.db import migrations, models

ACTIVE_APPLICATION_STAGES = [
    "pending_review",
    "needs_information",
    "ready_to_schedule",
    "interviewing",
    "first_interview_passed",
    "second_interview",
    "second_interview_passed",
    "offer_sent",
    "hired",
    "talent_pool",
]


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0008_interview_scheduling_core"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="expected_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="birthday",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="candidate",
            name="current_city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="candidate",
            name="current_salary",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="candidate",
            name="education_experience",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="education_level",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="candidate",
            name="expected_salary",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="candidate",
            name="gender",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="candidate",
            name="identity_number",
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AddField(
            model_name="candidate",
            name="intended_role",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="candidate",
            name="remarks",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="resume_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="school",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="candidate",
            name="work_experience",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="work_years",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveConstraint(
            model_name="application",
            name="application_closure",
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ("closed_at__isnull", False),
                        ("stage", "closed"),
                        models.Q(("close_reason", ""), _negated=True),
                    )
                    | models.Q(
                        ("close_reason", ""),
                        ("closed_at__isnull", True),
                        ("stage__in", ACTIVE_APPLICATION_STAGES),
                    )
                ),
                name="application_closure",
            ),
        ),
    ]
