# Generated by Django 5.2.17 on 2026-09-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0009_candidate_profile_intake_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="base_salary",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="commission_salary",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="company_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="job",
            name="job_level",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="performance_salary",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="job",
            name="planned_publish_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_range",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="job",
            name="total_monthly_salary",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
