# Generated by Django 5.2.17 on 2026-10-02 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0011_enterprise_enterpriseendorsement"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_key", models.UUIDField()),
                ("content", models.TextField(max_length=10000)),
                ("job_title", models.CharField(blank=True, max_length=120)),
                (
                    "dimension",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("专业能力", "专业能力"),
                            ("沟通表达", "沟通表达"),
                            ("逻辑思维", "逻辑思维"),
                            ("团队协作", "团队协作"),
                            ("抗压能力", "抗压能力"),
                            ("稳定性", "稳定性"),
                            ("岗位匹配度", "岗位匹配度"),
                            ("学习能力", "学习能力"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("简单", "简单"), ("中等", "中等"), ("困难", "困难")],
                        default="中等",
                        max_length=10,
                    ),
                ),
                ("reference_answer", models.TextField(blank=True, max_length=10000)),
                ("version", models.PositiveIntegerField(default=1)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="recruitment.organization"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="QuestionTemplateEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("action", models.CharField(max_length=20)),
                ("version", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="recruitment.membership"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="recruitment.questiontemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="questiontemplate",
            index=models.Index(fields=["organization", "deleted_at"], name="question_org_active"),
        ),
        migrations.AddConstraint(
            model_name="questiontemplate",
            constraint=models.UniqueConstraint(
                fields=("organization", "request_key"), name="one_question_creation_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="questiontemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="positive_question_version"
            ),
        ),
    ]
