# Generated by Django 5.2.17 on 2026-10-02 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0013_ai_screening"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileversion",
            name="activated_by_hr",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profilerequirement",
            name="generation_index",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profilerequirement",
            name="source_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profilerequirement",
            name="source_kind",
            field=models.CharField(default="manual", max_length=24),
        ),
        migrations.AddField(
            model_name="profilerequirement",
            name="source_quote",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profilerequirement",
            name="source_reference",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="profileversion",
            name="business_goal",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="ProfileGeneration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_key", models.UUIDField()),
                ("job_version", models.PositiveIntegerField()),
                ("purpose", models.CharField(default="job_profile_draft", max_length=32)),
                ("model", models.CharField(max_length=200)),
                ("prompt_version", models.CharField(max_length=40)),
                ("input_snapshot", models.JSONField()),
                ("status", models.CharField(default="running", max_length=16)),
                ("result", models.JSONField(default=list)),
                ("error", models.CharField(blank=True, max_length=500)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="recruitment.membership"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="profile_generations",
                        to="recruitment.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="profilerequirement",
            name="generation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="recruitment.profilegeneration",
            ),
        ),
        migrations.AddField(
            model_name="profileversion",
            name="generation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="recruitment.profilegeneration",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilegeneration",
            constraint=models.UniqueConstraint(
                fields=("job", "creator", "request_key"), name="one_profile_generation_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="profilegeneration",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["running", "succeeded", "failed", "stale"])),
                name="profile_generation_status",
            ),
        ),
    ]
