# Generated by Django 5.2.17 on 2026-10-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0016_ai_screening_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="profileversion",
            name="created_with_job",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profilegeneration",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="profile_generations",
                to="recruitment.job",
            ),
        ),
        migrations.AlterField(
            model_name="profilegeneration",
            name="job_version",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="profilegeneration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("purpose", "job_profile_preview")),
                fields=("creator", "request_key"),
                name="one_profile_preview_request",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilegeneration",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("job__isnull", True),
                        ("job_version__isnull", True),
                        ("purpose", "job_profile_preview"),
                    ),
                    models.Q(
                        ("job__isnull", False),
                        ("job_version__gte", 1),
                        ("job_version__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="profile_generation_job_version",
            ),
        ),
    ]
