# Generated by Django 5.2.17 on 2026-10-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0017_profile_ai_preview"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="resumedocument",
            name="resume_file_state",
        ),
        migrations.AddField(
            model_name="candidate",
            name="creation_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="candidate",
            name="request_key",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="source",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="resumedocument",
            name="request_key",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="candidate",
            constraint=models.UniqueConstraint(
                fields=("organization", "request_key"), name="candidate_creation_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="resumedocument",
            constraint=models.UniqueConstraint(
                fields=("uploaded_by", "request_key"), name="resume_preview_request"
            ),
        ),
        migrations.AddConstraint(
            model_name="resumedocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("access_state__in", ["active", "quarantine", "deleted"]),
                    ("file_type__in", ["pdf", "docx", "txt", "doc", "jpg", "jpeg", "png"]),
                ),
                name="resume_file_state",
            ),
        ),
    ]
