# Generated by Django 5.2.17 on 2026-10-09 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recruitment", "0021_feishu_department_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="profile_resume_parse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="recruitment.resumeparse",
            ),
        ),
        migrations.CreateModel(
            name="CandidateEditRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_key", models.UUIDField()),
                ("input_digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="recruitment.membership"
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="recruitment.candidate"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("candidate", "actor", "request_key"),
                        name="one_candidate_edit_request",
                    )
                ],
            },
        ),
    ]
