# Generated by Django 5.2.17 on 2026-10-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0022_candidate_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilerequirement',
            name='category',
            field=models.CharField(choices=[('education', '学历门槛'), ('experience', '工作年限'), ('industry', '行业背景'), ('skill', '技能'), ('other', '其他要求')], default='other', max_length=20),
        ),
    ]
