# Generated by Django 5.2.17 on 2026-10-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0023_profilerequirement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
